services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_URL: 'jdbc:postgresql://localhost:5432/book_db_dev'
      POSTGRES_DB: book_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      driver-class-name: org.postgresql.Driver

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5

  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  rabbitmq_data: